"""empty message

Revision ID: f85da112dea2
Revises: 
Create Date: 2021-04-19 20:07:46.491337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85da112dea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('product_cost', sa.Integer(), nullable=False),
    sa.Column('product_image', sa.String(length=250), nullable=True),
    sa.Column('product_upc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_cost'),
    sa.UniqueConstraint('product_upc')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('keepaapi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_upc', sa.Integer(), nullable=True),
    sa.Column('fba_fee', sa.Integer(), nullable=False),
    sa.Column('amazon_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_upc'], ['products.product_upc'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amazon_price'),
    sa.UniqueConstraint('fba_fee')
    )
    op.create_table('userhasproducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_cost', sa.Integer(), nullable=True),
    sa.Column('fba_fee', sa.Integer(), nullable=True),
    sa.Column('amazon_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amazon_price'], ['keepaapi.amazon_price'], ),
    sa.ForeignKeyConstraint(['fba_fee'], ['keepaapi.fba_fee'], ),
    sa.ForeignKeyConstraint(['product_cost'], ['products.product_cost'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profit')
    op.drop_table('userhasproducts')
    op.drop_table('keepaapi')
    op.drop_table('user')
    op.drop_table('products')
    # ### end Alembic commands ###
