"""empty message

Revision ID: f8e09b7cf7b5
Revises: 
Create Date: 2021-04-23 15:42:20.800724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e09b7cf7b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('product_cost', sa.String(length=10), nullable=False),
    sa.Column('product_image', sa.String(length=250), nullable=True),
    sa.Column('product_upc', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_upc')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('keepaapi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_upc', sa.String(length=12), nullable=True),
    sa.Column('fba_fee', sa.String(length=10), nullable=False),
    sa.Column('amazon_price', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['product_upc'], ['products.product_upc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userhasproducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('keepaAPI_id', sa.Integer(), nullable=True),
    sa.Column('product_cost', sa.String(length=10), nullable=False),
    sa.Column('fba_fee', sa.String(length=10), nullable=False),
    sa.Column('amazon_price', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['keepaAPI_id'], ['keepaapi.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profit')
    op.drop_table('userhasproducts')
    op.drop_table('keepaapi')
    op.drop_table('user')
    op.drop_table('products')
    # ### end Alembic commands ###
